import { FaqBlock } from "./faq-block";

export function FaqList(){
    return (
        <div className="flex flex-col gap-6 px-[80px] pt-[70px]">
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="What is cryptocurrency?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
        </div>
    )
}