import { FaqBlock } from "./faq-block";

export function FaqList(){
    return (
        <div className="flex flex-col gap-6 2xl:px-20 xl:px-16 lg:px-12 md:px-10 sm:px-8 px-6 md:pb-0 pb-[52px] pt-[140px]">
            <FaqBlock title="What is cryptocurrency?" text="Cryptocurrency is a type of virtual currency that uses cryptography to secure transactions that are digitally recorded on a distributed ledger, such as a blockchain. A transaction involving cryptocurrency that is recorded on a distributed ledger is referred to as an “on-chain” transaction; a transaction that is not recorded on the distributed ledger is referred to as an “off-chain” transaction."/>
            <FaqBlock title="How to log in to your account?" text="Go to /login . In this window, enter your e-mail address, password, and captcha. Click the Login button. You logged in to your account. Now you can make a deposit or start trading. We also recommend you to log into your personal account and enable the two-factor authentication. More information can be found at the link: /about"/>
            <FaqBlock title="How to register an account?" text="Go to /register . In this window, enter your e-mail address, password, password confirmation, captcha and agree to the Terms of Use. Click the Sign Up button. Welcome to the Exchange!"/>
            <FaqBlock title="Can I delete my account?" text={`This option is not available. You can block the account. To do this, you can create a corresponding ticket in the technical support, where you need to specify a valid e-mail as well as the KYC data. To create a ticket, press on the blue button of "Support" in the right down corner of the page.`}/>
            <FaqBlock title="How to make a currency withdrawal on the exchange?" text={`Go to the Balance tab and click on the "Withdraw" next to the desired coin, enter the address and the amount.`}/>
            <FaqBlock title="On what terms are the requests for withdrawal being processed?" text="After the identity verification, all applications will be made within 24 hours."/>
            <FaqBlock title="How do I cancel a withdrawal request?" text="This option is not available. You can still contact our support, we will do everything possible to help you solve the issue."/>
            <FaqBlock title="How do I replenish my balance?" text={`Go to the Balance tab at the top of the page. To replenish your balance, click "Deposit" next to the desired coin.`}/>
            <FaqBlock title="How long does it take to receive a response from the support team? How does it work?" text="For the convenience of our users, we have a customer support service that works 7 days a week and 24 hours a day without breaks and holidays. If you have any questions, wishes or suggestions, our specialists are always ready to help you with any problem, and also to hear your suggestions for improving the service. We will do our best to reply ASAP."/>
            <FaqBlock title="Can I connect a bank account to my account?" text="Unfortunately, this option is currently unavailable on our exchange."/>
            <FaqBlock title="How to enable the two-factor authentication?" text={`Download the Google Authenticator application from Play Market or AppStore. Go to your Account (to do this you need to click on your email in the top right corner) and then choose the Security section. Scan the QR code in the downloaded application or enter the number manually. After the "Binarrian" tab appears in the app, enter the authentication code in the “Please Enter Key” field. All set, you enabled the two-factor authentication!`}/>
            <FaqBlock title="What if I lost the code / key to two-factor authentication?" text="You need to provide KYC data, account login, as well as data of the latest currency deposits and withdrawals and send this information to support."/>
            <FaqBlock title="Is it safe to use Binarrian exchange?" text="Yes! The main priority in our work is the security of our clients personal data and safety. We use advanced methods and technologies in the field of security. We implemented two-factor authentication technology to protect your accounts, as well as Anti Phishing, which helps to ensure the reliability of our exchange. More than 95% of all currency is stored on cold wallets. WAF (Web Application Firewall) - a protective screen of a Web application that detects and blocks hacker attacks."/>
            <FaqBlock title="What is two-factor authentication?" text="Two-factor authentication is an additional resource that allows you to access your account, even if someone else has access to your password. When you log in to your account, you will be offered two pieces of information: your password and a 6-digit authentication code. The authentication app generates new authentication code every 30 seconds. We strongly recommend that all our users enable this security feature to prevent any potential unauthorized access to their accounts. This function is necessary to ensure the security of your assets, so please take the time to set it up as soon as possible!"/>
            <FaqBlock title="What is KYC and why is it needed?" text="Know your customer (abbreviated KYC) is the term of banking and exchange regulation for financial institutions and bookmakers, as well as other companies working with private money, meaning that they must identify and establish the identity of the counterparty before conducting a financial transaction.This requirement extends to obtaining reasonably complete information about counterparties-legal entities, the nature of their business and certain business transactions for which a financial transaction is being conducted."/>
            <FaqBlock title="I did a deposit several days ago, but it still hasn't been received. What do I do?" text="Please send us a hash of your transaction and we will check all the information."/>
            <FaqBlock title="I can not cancel the Order / Tokens were not credited to the account" text="Please create ticket in our support with a screenshot of the order, or of the errors attached. We will try to resolve your issue as soon as possible."/>
            <FaqBlock title="Can I cancel an Order?" text="Yes, to cancel an order, please go to the Orders page at the top of the page. Please note that you can only cancel those orders that have not yet been accepted, since once the order is executed, such transaction is irreversible and can not be canceled."/>
            <FaqBlock title="Where can I see the history of my orders?" text="You can see the history of your transactions on the Trading page in the My trades tab."/>
            <FaqBlock title="I issued a Buy Order for 100 coins, with only 20 coins credited to me. Why?" text="A partial completion of the Order took place. Please wait till the Order for the rest of the coins is accepted."/>
            <FaqBlock title="When will my Order be processed?" text="Please pay attention that the administration of the site does not accept, control or interfere with trading on the exchange. Please wait until another user accepts your Order. Alternatively, you can cancel an open order and submit a new order with a more competitive price."/>
            <FaqBlock title="I placed an order, but for some reason, it is not accepted, although I can see cheaper Buy Orders being already processed. Why?" text="Orders can only be purchased by users of the exchange, the administration of the site does not accept, control or interfere with trading on the exchange. If you want to speed up the process, you can cancel the open Order and submit a new order with a more competitive price."/>
            <FaqBlock title="Where can I see Buy Orders?" text="Buy Orders will be displayed on the main page, or in the Trade tab."/>
            <FaqBlock title="How to create an Order?" text={`To create an order, go to the Trade section of the main page. You can select the cryptocurrency in the "Market" window by double-clicking on the desired coin. On this page you can see the forms for buying and selling cryptocurrency. Please pay attention that the Order to buy or sell can not exceed your balance. On this page, you can also see windows showing actual Buy/Sell Orders of other users of our exchange. Note that the rate is not fixed, since Binarrian is an exchange, not an exchanger, so the rates are formed based on the orders placed by other users on the Trade page. After placing an order, you can see it either on the Trade page, in the "My Orders" window: Or on the Orders page.`}/>
            <FaqBlock title="What is the trading fee?" text="You will see the fee for your transaction before you execute the order."/>
            <FaqBlock title="Is there any transaction limit? What is the maximum / minimum amount of the transaction?" text="The min. and max. order amount varies for each trading pair and can be seen at the Trade Page when placing an Order."/>
        </div>
    )
}