import {HomeHero} from "@/features/home/home-hero.tsx";
import {IndiceSection} from "@/features/indices/indice-section.tsx";

export function PrivacyPolicyPage(){
    return (
        <div
            className="flex flex-col sm:mb-0 mb-[100px] 2xl:px-20 xl:px-16 lg:px-12 md:px-10 sm:px-8 px-6 relative overflow-y-hidden overflow-x-hidden gap-[100px]">
            <HomeHero title="Privacy Policy" padding="2xl:pt-[100px] lg:pt-[90px] md:pt-0"/>
            <img className="self-center xl:pt-[200px] sm:pt-[100px] pt-[50px]" src="/img/privacy-policy.svg"
                 alt="cookies"/>

            <div className="flex flex-col lg:gap-9 md:gap-16 sm:gap-20 gap-24">
                <IndiceSection title="General"
                               text="Binarrian Financial Company and its affiliates (hereinafter, 'Binarrian Financial Company', 'Binarrian', 'we', 'us' or 'our') are committed to protecting and respecting your privacy. This Privacy Policy (together with our Terms of Use) governs our collection, processing and use of your Personal Information. We define 'Personal Information' as information which identifies you personally, e.g. your name, address, e-mail address, trades etc."/>
                <IndiceSection title="Who is Binarrian"
                               text="Binarrian is Australia’s largest fully regulated and licensed AML/CTF compliant AUSTRAC registered Dual Gateway Exchange Platform. Buy, sell, send, receive and trade cryptocurrencies."/>
                <IndiceSection title="The types of Personal Information which we collect may include:"
                               text="We will process your Personal Information only for the purpose(s) of providing to you the service(s) that you ask us to provide you and to satisfy the legal obligations stemming from regulatory obligations that arise from providing you the service(s)"/>
                <IndiceSection title="IP Addresses"
                               text="We may collect information about your computer, including where available your IP address, operating system and browser type, for system administration and to report aggregate information to our advertisers. This is statistical data about our users' browsing actions and patterns and will not be used to identify any individual unless that same individual."/>
                <IndiceSection title="Cookies"
                               text="We use a browser feature known as a 'cookie', which assigns a unique identification to your computer. Cookies are typically stored on your computer's hard drive. Information collected from cookies is used by us to evaluate the effectiveness of our Site, analyze trends, and administer the Platform. The information collected from cookies allows us to determine such things as which parts of our Site are most visited and difficulties our visitors may experience in accessing our Site. With this knowledge, we can improve the quality of your experience on the Platform by recognizing and delivering more of the most desired features and information, as well as by resolving access difficulties. We also use cookies and/or a technology known as web bugs or clear gifs, which are typically stored in emails to help us confirm your receipt of, and response to, our emails and to provide you with a more personalized experience when using our Site. We use third party service provider(s), to assist us in better understanding the use of our Site. Our service provider(s) will place cookies on the hard drive of your computer and will receive information that we select that will educate us on such things as how visitors navigate around our site, what products are browsed, and general Transaction information. Our service provider(s) analyses this information and provides us with aggregate reports. The information and analysis provided by our service provider(s) will be used to assist us in better understanding our visitors' interests in our Site and how to better serve those interests. The information collected by our service provider(s) may be linked to and combined with information that we collect about you while you are using the Platform. Our service provider(s) is/are contractually restricted from using information they receive from our Site other than to assist us. By using our Site you are agreeing that we may use cookies for the purposes set out above. The company will keep records of all transfers of Personal Information to third parties and this information, where possible, can be provided to you."/>
                <IndiceSection title="Disclosure of Personal Information" text="We use the Personal Information for the purposes indicated at the time you provide us with such information, and/or otherwise for the purposes set out in this Privacy Policy, and/or as otherwise permitted by law.
                    We may make the Personal Information you provide available to our affiliates, agents, representatives, trusted service providers, and contractors for these limited purposes, either with your express consent or as necessary to deliver the service you have requested.
                    We may also share Users’ Personal Information with financial institutions, insurance companies, or other entities in the case of a merger, divestiture, or other corporate reorganisation. In such cases, we will notify you of the sharing of your information, so you may exercise any applicable rights.
                    Additionally, we may disclose Users' Personal Information to law enforcement or regulatory authorities, as required by law. Due to legal restrictions, we may not be able to inform you of such disclosures.
                    Any third party that receives or gains access to Personal Information will be required by Binarrian to protect that information and to use it only for the purpose of delivering services to you or to Binarrian, unless otherwise required or permitted by law.
                    Such third parties, excluding regulatory bodies, will be contractually obligated to adhere to the same confidentiality and security standards as Binarrian and to assume equivalent responsibilities.
                    Where you exercise any of your rights with respect to Binarrian, we will ensure that such rights are also recognized and upheld by any third parties who have access to your Personal Information.
                    We will make sure that any such third party is aware of our obligations under this Privacy Policy, and we will enter into contractual agreements with them that impose data protection obligations no less protective than those we commit to under this Privacy Policy or as required by applicable data protection laws."/>
                <IndiceSection title="Your rights" text="You have the right to access your Personal Information and to request the correction, updating, or blocking of any inaccurate or incorrect data. You may do so by sending an email to the address provided on our website (our official email), or by using the relevant features available in your account profile page (if applicable).
                    Upon your written request to our email, we will inform you of the Personal Information we hold about you, including how we use and generally disclose it. We will also provide you with a copy of the retained Personal Information. A minimal administrative fee may be charged for any additional copies you request.
                    You may also request the deletion or destruction of both your Account and your Personal Information by contacting us via email. Binarrian will process your request promptly, unless doing so would conflict with our legal or regulatory obligations.
                    You also have the right to request that your Personal Information be transferred to another data controller of your choice.
                    To protect the confidentiality, integrity, and availability of your information, we may require you to verify your identity by providing valid identification documentation or through other verification methods before we assist you in exercising your rights. If you decline to verify your identity, we may refuse to act on your request—except to restrict further processing—until we can be confident the request genuinely originates from the data subject.
                    In delivering our services, Binarrian may use automated decision-making and profiling to help detect and reduce the risks of fraud, money laundering, or misuse of our platform. This may include analyzing your identification, transaction patterns, and behavioral data.
                    Please note that we may be unable to provide you with some or all services if you do not consent to this automated processing. If you believe such processing may negatively affect you, you may request more information about the nature and scope of this automated decision-making by contacting us via email."/>
                <IndiceSection title="Security" text="We have implemented appropriate technical and organizational security measures to ensure the confidentiality, integrity, and availability of your Personal Information, and to protect it from loss, misuse, unauthorized access, alteration, or destruction.
                    Access to your Personal Information is strictly limited to authorized personnel of Binarrian, all of whom are required to treat such information as strictly confidential.
                    Where you have given consent, or where we are legally or contractually required to share your Personal Information with third parties—such as in the provision of a requested service or in compliance with legal or regulatory obligations—we will ensure, where possible, that equivalent technical and organizational safeguards are implemented by those third parties through appropriate contractual arrangements.
                    Our security measures are regularly reviewed and updated in line with technological advancements and changes in applicable laws and regulations.
                    In the event of a personal data breach or failure of our protective measures that results in a risk to your rights and freedoms, we will notify you without undue delay and in accordance with our legal obligations."/>
                <IndiceSection title="Links"
                               text="Here may be links from our Site to other sites and resources provided by third parties. This Privacy Policy applies only to our Site. Accessing those third-party sites or sources requires you to leave our Site. We do not control those third party sites or any of the content contained therein and you agree that we are in no way responsible or liable for any of those third party sites, including, without limitation, their content, policies, failures, promotions, products, services or actions and/or any damages, losses, failures or problems caused by, related to or arising from those sites. We encourage you to review all policies, rules, terms and regulations, including the privacy policies, of each site that you visi"/>
                <IndiceSection title="Retention of Personal Information" text="Your information is stored on our secure servers. Access to this information is granted only to authorized employees of Binarrian, whose offices may be located both within and outside the European Union. All such employees are required to adhere to data security principles and procedures equivalent to those applicable within the EU.
                    We will retain your Personal Information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy and to comply with our legal and regulatory obligations.
                    In accordance with applicable requirements related to Anti-Money Laundering (AML), taxation, and corporate law, Binarrian will retain user accounts and related Personal Information for a minimum period of ten (10) years following the closure of your account.
                    Any data stored solely for regulatory compliance purposes will be appropriately protected from unnecessary processing and retained only to meet information disclosure obligations to competent authorities, if and when required."/>
                <IndiceSection title="Disposal of Personal Information"
                               text="Once we do not have any obligation to providing you with a service you requested, nor an obligation to hold Personal Information for regulatory or legal purpose, we will anonymize or dispose of your Personal Information in line with acceptable industry and security standards so that this cannot be subsequently retrieved and associated to you. Where we cannot directly remove such records, such as in archived backups, we will retain a log of which Personal Information should be removed if ever the backup data is restored."/>
                <IndiceSection title="Marketing"
                               text="We will ask you for your consent on registration or post-registration, by providing you the ability to check marketing preferences check boxes located within your account profile page to allow us to contact you or use your Personal Information for marketing purposes. You have the right to retract the consent for us to process your Personal Information for marketing purposes. You can exercise your right to prevent such processing by unchecking marketing preferences check boxes on your account profile or by contacting us at any time on our e-mail."/>
                <IndiceSection title="Our Data Protection Officer" text="Our Data Protection Officer (DPO) is responsible for ensuring that Binarrian complies with the obligations outlined in this Privacy Policy and applicable data protection regulations. The DPO also serves as the primary point of contact for communications with the relevant Data Protection Supervisory Authority.
                    You may contact our Data Protection Officer at the following email address: dpo@binarrian.com."/>
                <IndiceSection title="Data Protection Supervisory Authority"
                               text="You may contact an appropriate Data Protection Supervisory Authority if you wish to discuss with them any instance where you feel we may not be adhering to the terms within this Privacy Policy or to raise a complaint."/>
                <IndiceSection title="Changes" text="The policies, content, information, features, disclosures, and disclaimers on our Site may be revised, updated, modified, or supplemented at any time, at the sole discretion of Binarrian, without prior notice. If we make material changes to this Privacy Policy, we will notify users by placing a prominent notice on our website and by posting the updated version of the Privacy Policy.
                    Where such changes may significantly affect your rights or the way we process your Personal Information, we will request your acknowledgment and acceptance of the amended Privacy Policy before continuing our relationship with you."/>
                <IndiceSection title="Fraud, Phishing and Email scams disclaimer" text="Please be advised that Binarrian is not affiliated with any third-party individuals or entities who claim to offer customer support services via phone, social media, or other unofficial channels—especially those requesting payment for assistance.
                    All official customer support is provided exclusively through the Binarrian website and is always free of charge. We strongly advise users not to share personal or account information with any individuals claiming to represent Binarrian outside of our verified support channels.
                    If you encounter any suspicious activity or receive fraudulent offers of support, please report them immediately to our official support team through our website."/>
                <IndiceSection title="Contact Us"
                               text="If you have any questions, comments, or concerns not specifically regarding our Privacy Policy and/or practices as it or they relate to the Platform, please contact us at our email address."/>
            </div>

            <img className="absolute top-[850px] left-0" src="/img/elipse-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[850px] right-0"
                 src="/img/elipse-light-about.png" alt="light"/>
            <img className="absolute top-[850px] right-[0px]" src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[1550px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
            <img className="absolute top-[3400px] right-[0px]" src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[5250px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
            <img className="absolute top-[6700px] right-[0px]" src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[7050px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
            <img className="absolute top-[9000px] right-[0px]" src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[1530px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
            <img className="absolute top-[1260px] right-[0px]" src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[2030px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
            <img style={{transform: "scaleX(-1)"}} className="absolute top-[3330px] left-[-100px]"
                 src="/img/round-light-about.png" alt="light"/>
        </div>
    )
}

export default PrivacyPolicyPage;